# -*- coding: utf-8 -*-
"""ImageRecognition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sGoEy8Vdo4gk246hnHniGa0jePmd47Hq
"""

import tensorflow as tf
import numpy as np

filename = "/content/Cat1.PNG"

"""**Loding image** **by Ipython**"""

from IPython.display import Image
Image(filename='/content/Cat1.PNG', width=224, height=224)

"""**Loding image by Keras**"""

from tensorflow.python.ops.gen_array_ops import size
from tensorflow.keras.preprocessing import image
img = image.load_img(filename, target_size=(224,224))
img

import matplotlib.pyplot as plt

plt.imshow(img)

"""**Loding image by cv2**"""

import cv2

imgg= cv2.imread(filename)
plt.imshow(imgg)

imgg= cv2.resize(imgg, (224,224))
plt.imshow(cv2.cvtColor(imgg,cv2.COLOR_BGR2RGB))

"""**Loading the model**"""

mobile = tf.keras.applications.mobilenet.MobileNet() ##deep learning model weights pre- trained

"""t **1- create a model
2- train the model
3- test and validate the model 
4- predic**
"""

mobile = tf.keras.applications.mobilenet_v2.MobileNetV2()

"""**preprocessing the images**"""

from tensorflow.python.ops.gen_array_ops import size
from tensorflow.keras.preprocessing import image
img = image.load_img(filename, target_size=(224,224))

resized_img = image.img_to_array(img)
final_image = np.expand_dims(resized_img, axis=0)
final_image = tf.keras.applications.mobilenet.preprocess_input(final_image)

final_image.shape

predictions= mobile.predict(final_image)

from tensorflow.keras.applications import imagenet_utils

results = imagenet_utils.decode_predictions(predictions)

results